
export const dummyHabits = [
    {
        id: '10',
        name: 'Read',
        units: '20',
        type: types[0],
        icon: 'home',
        frequency: frequencies[0],
        active: true,
    },
    {
        id: '11',
        name: 'Spanish',
        units: '15',
        type: types[0],
        icon: 'language',
        frequency: frequencies[0],
        active: true,
    },
    {
        id: '12',
        name: 'Read',
        units: '20',
        type: types[0],
        icon: 'home',
        frequency: frequencies[0],
        active: true,
    },
    {
        id: '13',
        name: 'Spanish',
        units: '15',
        type: types[0],
        icon: 'language',
        frequency: frequencies[0],
        active: true,
    },
    {
        id: '14',
        name: 'Spanish Review',
        units: '30',
        type: types[0],
        icon: 'language',
        frequency: frequencies[1],
        active: true,
    },
    {
        id: '15',
        name: 'HIIT Exercise',
        units: '2',
        type: types[1],
        icon: 'directions-run',
        frequency: frequencies[0],
        active: true,
    },
    {
        id: '16',
        name: 'DEV Articles',
        units: '30',
        type: types[0],
        icon: 'laptop',
        frequency: frequencies[0],
        active: false,
    },
];
